project_id = "arlrfyrcxxxmhaeqetcr"

[functions.get-public-video-otp]
verify_jwt = false

[functions.get-billing-info]
verify_jwt = false

[functions.admin-api]
verify_jwt = false

[functions.check-access]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = false

[functions.free-coupon-checkout]
verify_jwt = false

[functions.get-video-otp]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.validate-coupon]
verify_jwt = false

[functions.check-email-exists]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true
